---
title: "Introduction to association studies"
output: ioslides_presentation
---

## Association studies

How are various factors related to an outcome?

- Small number of measured covariates believed to be important in predicting outcome

What factors are related to an outcome?

- Large number of measured covariates, many of which have uncertain link to outcome

<div class="notes">
Emphasize the variability that manifests at every stage
</div>

## Research question in the press

How does influenza strain exposure in childhood affect the risk of being infected with and dsevere H5N1 or H7N9 in adulthood and its severity?

## Research question from initial investigation

From the Science editorial:

> "This [hemagglutinin] difference parallels intriguing epidemiological differences: A/H5N1 cases are found mainly in children and young adults, whereas A/H7N9 cases areconcentrated in older individuals. These contrasting age profiles have sparked several hypotheses, including the effect of age-specific contacts with infected birds for A/H7N9 (2) and previous immunity to the neuraminidase surface protein for A/H5N1 (3)."

Why are older people more likely to be infected with one strain and younger people more likely to be infected with the other strain?

## Thought process

What are the characteristics of the older people (who tended to be infected with H7) and of the younger people (who tended to be infected with H5)?

What characteristics can we look at?

<div class="notes">
Prompt the class to think of characteristics that might explain this differential infection. Write these on the board. These covariates are good candidates for variables that should be adjusted for in the statistical analysis. Prompt the students to recall the uses of regression.
</div>

## Key domain-specific knowledge

From the original Science paper:

> "recent experiments have revealed that broadly protective immune responses can provide cross-immunity between different HA subtypes, particularly subtypes in the same phylogenetic group"

Group 1: seasonal H1 and H2; avian H5
Group 2: seasonal H3; avian H7

This knowledge prompted the researchers to ask: does the subtype of an individual's first influenza exposure affect immunity to avian flus H5 and H7?

Does data on this exist?

<div class="notes">
What if the researchers had not known about this recent research?
</div>

## What would the data need to look like?

For studying immunity to H5:

```{r echo=FALSE}
df <- data.frame(id = 1:10, diedFromH5 = sample(c("died", "lived"), 10, replace = TRUE), firstFluExp = sample(c("H1", "H2", "H3"), 10, replace = TRUE))
df
```

But `firstFluExp` is not available...directly.

## What needed to be done?

From the Science editorial:

> "Using historical influenza epidemiological records, Gostic et al. carefully reconstruct the susceptibility of each birth cohort based on the likelihood that their primary infection was with group 1 or 2 HA influenza"

<div class="notes">
The CNN article doesn't give a lot of detail. It is almost always necessary to go back to the original study.
</div>

<div class="notes">
For the p_yci

- strain prevalence by year and country
- age-specific poultry exposure rates by year

y = calendar year in which H5 or H7 infection occurred
c = country
i = birth cohort (calendar year of birth)

p_yci = probability of {H5,H7} infection (death or fatality) for an individual who had that aforementioned avian flu infection in calendar year y, in country c, and was born in year i
- Outcome vector has length equal to the number of birth years represented in the data. D_yc has the same length and describes the proportion of people born in each of those years (sum(D_yc)=1). Had poultry exposure rates by age group, so this would also form a vector of the same length
- For y,c in calendar_year_of_avian_flu_infection,country: fit multinomial model:
birth_year(i) num_H5_infects(outcome) demography poultry_exposure age_risk frac_HA_imprint frac_NA_imprint
1950
1951
.
.
1967

"Normalization of data to demographic age distribution" section just explains how "excess cases" in Figure 2C, D was calculated
</div>

## Points to evaluate

- Outcome
- Subjects
- Predictors
- Analysis
- Conclusions
- What the study did not do

## Outcome

- Is it continuous, binary, categorical? Answer determines what types of models can be fit
- How many outcomes are being studied?
- Ideal outcome or an outcome of convenience?
- Is there a chance that the outcome was ascertained with error?

## Outcome variable type

Generalized linear models (GLMs) represent a broad framework of regression models where many different types of outcomes can be studied.

**Linear regression**

$$ E[\mathrm{continuous\:outcome}] = \beta_0 + \beta_1\mathrm{predictor}_1 + \cdots + \beta_p\mathrm{predictor}_p $$

**Logistic regression**

$$ log \left( \frac{E[\mathrm{binary\:outcome}]}{1 - E[\mathrm{binary\:outcome}]} \right) = \beta_0 + \beta_1\mathrm{predictor}_1 + \cdots + \beta_p\mathrm{predictor}_p $$

**Generalized linear model**

$$ \mathrm{function}(E[\mathrm{other\:type\:of\:outcome}]) = \beta_0 + \beta_1\mathrm{predictor}_1 + \cdots + \beta_p\mathrm{predictor}_p $$

What type of variable is used to measure immunity?

<div class="notes">
A binary variable - presence or absence of infection
</div>

## Choice of outcome studied

First try to imagine what the ideal outcome to measure would be. Then compare to what was actually done. Are you satisfied or not?

Data for some types of outcomes are more readily availble than others

- Medical information: physician diagnosis rather than patient report
- Extreme events rather than more typical ones

Somtimes researchers categorize a continuous variable

## Choice of outcome studied {.build}

Researchers only had access to severe cases of flu ("clinical and fatal cases of H5N1 and H7N9").

So really they were studying the relationship between immunity to **extreme** H5/H7 and first influenza exposure.

## Outcome ascertainment

- Did outcome ascertainment require subjects to rely on memory? (recall bias)
- What are the accuracy characteristics of the technologies measuring the outcomes?
- How complete/accurate is the historical data being used to obtain outcomes?

## Number of outcomes

One approach to analyzing multiple outcomes is to combine them into a score.

When should a variable be a covariate and when should it define multiple levels over which to fit separate models?

## Study subjects

How were subjects selected?

- Was the study observational or randomized?
- Enrollment criteria

Often there is bias in the type of people who end up in the study. We can try to

- limit the generalizability we perceive
- create a lower or upper bound on the overall effect

<div class="notes">
In observational studies, we don't control which subjects experience the exposure.
</div>

## Predictors

- Do the predictors encompass the set of variables that should reasonably be associated with the outcome?
- How well are the predictors measured/ascertained?

## Analysis

Identify the method(s) used and the associated assumptions. Are there any features of the data that lead you to question the validity of those assumptions?

## Conclusions {.build}

Are the conclusions something we should care about?

Example: reports about movie earnings at the box office. Can we compare earnings from movies made in different years?

An example of such thinking in action: [Hillary Clinton set to receive more votes than any US presidential candidate in history except Barack Obama](http://www.independent.co.uk/news/world/americas/us-elections/us-election-hillary-clinton-more-votes-popular-vote-any-candidate-barack-obama-donald-trump-a7413596.html)

## Conclusions

Can you identify any conclusions that should have associated estimates of uncertainty?

From CNN:

> "If you were exposed to a certain flu strain in your childhood, that first exposure could have resulted in long-term protection against related flu viruses, reducing your risk of a future severe infection by up to 75%"

## Conclusions

Are appropriate reference/control conditions provided to give context for what we should expect?